package smartgrid.newsimcontrol.rmi;
import org.apache.log4j.Logger;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.debug.core.ILaunchConfiguration;

import couplingToICT.PowerAssigned;
import couplingToICT.PowerSpecContainer;
import couplingToICT.SmartComponentStateContainer;
import couplingToICT.SmartGridTopoContainer;
import smartgrid.log4j.LoggingInitializer;
import smartgrid.newsimcontrol.controller.ReactiveSimulationController;
import smartgrid.newsimcontrol.rmi.server.BlockingDataExchanger;
import smartgrid.simcontrol.test.baselib.Constants;

// TODO add JavaDoc Description
public final class ActiveSimulationController {

    private static final Logger LOG = Logger.getLogger(ActiveSimulationController.class);

    private ReactiveSimulationController reactiveSimControl;

    private int maxTimeSteps;

    public void run() throws InterruptedException {
        
    	PowerAssigned powerAssigned;
        powerAssigned = BlockingDataExchanger.getPowerAssigned();

			SmartComponentStateContainer scsc = null;
			
	        // one iteration computes one timestep
	        for (int timeStep = 0; timeStep < maxTimeSteps; timeStep++) {
	        	scsc = reactiveSimControl.run(powerAssigned); 
	        }
	        
	        BlockingDataExchanger.storeSCSC(scsc);
	        PowerSpecContainer bufferedPowerSpecs = BlockingDataExchanger.getBufferedPowerSpecs();
	        PowerSpecContainer modifiedPowerSpecs = reactiveSimControl.modifyPowerSpecContainer(bufferedPowerSpecs);
	        BlockingDataExchanger.storeModifiedPowerSpecs(modifiedPowerSpecs);
	
	        LOG.info("Coupled simulation terminated internally");
    }

    public void init(final ILaunchConfiguration launchConfig) throws CoreException, InterruptedException {

        LoggingInitializer.initialize();

        LOG.debug("init active launch config");

        // read config options
        String outputPath = launchConfig.getAttribute(Constants.OUTPUT_PATH_KEY, "");
        String inputPath = launchConfig.getAttribute(Constants.INPUT_PATH_KEY, "");
        String topoPath = launchConfig.getAttribute(Constants.TOPO_PATH_KEY, "");
        boolean generateTopo = launchConfig.getAttribute(Constants.TOPO_GENERATION_KEY, false);
        maxTimeSteps = Integer.parseUnsignedInt(launchConfig.getAttribute(Constants.TIME_STEPS_KEY, ""));

        LOG.info("Running for " + maxTimeSteps + " time steps");

        reactiveSimControl = new ReactiveSimulationController();
        reactiveSimControl.init(outputPath);

        reactiveSimControl.loadCustomUserAnalysis(launchConfig);

        if (generateTopo) {
            //reactiveSimControl.initModelsAutogenerated();
        	SmartGridTopoContainer topoContainer = BlockingDataExchanger.getTopoData();
        	reactiveSimControl.initTopo(topoContainer);
        } else {
            reactiveSimControl.initModelsFromFiles(topoPath, inputPath);
        }

        //kritisSimulation = TestSimulationExtensionPointHelper.findExtension(launchConfig, TestSimulationExtensionPointHelper.getKritisSimulationExtensions(), Constants.KRITIS_SIMULATION_KEY,
        //        IKritisSimulationWrapper.class);
        //kritisSimulation.init(launchConfig);
        //LOG.info("Using KRITIS simulation: " + kritisSimulation.getName());
    }

    public void shutDown() {
        LOG.info("Coupled simulation terminated externally");
        reactiveSimControl.shutDown();
    }
}
