<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="topoextension" nsURI="http://sdq.ipd.uka.de/smartgridtopo/topoextension"
    nsPrefix="topoextension">
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="replications" upperBound="-1"
        eType="#//Replication" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="completion" upperBound="-1"
        eType="#//Completion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Replication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nrOfReplicas" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Completion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkentity" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../smartgrid.model.topo/model/smartgridtopo.ecore#//NetworkEntity"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
