/**
 *
 * $Id$
 */
package smartgridinput.validation;

import org.eclipse.emf.common.util.EList;

import smartgridinput.EntityState;
import smartgridinput.PowerState;

import smartgridtopo.SmartGridTopology;

/**
 * A sample validator interface for {@link smartgridinput.ScenarioState}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ScenarioStateValidator {
	boolean validate();

	boolean validateEntityStates(EList<EntityState> value);
	boolean validatePowerStates(EList<PowerState> value);
	boolean validateScenario(SmartGridTopology value);
}
