/**
 *
 * $Id$
 */
package smartgridoutput.validation;

import org.eclipse.emf.common.util.EList;

import smartgridoutput.On;

/**
 * A sample validator interface for {@link smartgridoutput.Cluster}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClusterValidator {
	boolean validate();

	boolean validateControlCenterCount(int value);
	boolean validateSmartMeterCount(int value);
	boolean validateHasEntities(EList<On> value);
}
