/**
 *
 * $Id$
 */
package smartgridtopo.validation;

import org.eclipse.emf.common.util.EList;

import smartgridtopo.PhysicalConnection;
import smartgridtopo.PowerGridNode;

/**
 * A sample validator interface for {@link smartgridtopo.NetworkEntity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NetworkEntityValidator {
	boolean validate();

	boolean validateConnectedTo(EList<PowerGridNode> value);
	boolean validateLinkedBy(EList<PhysicalConnection> value);
}
