/**
 *
 * $Id$
 */
package smartgridtopo.validation;

import org.eclipse.emf.common.util.EList;

import smartgridtopo.ConnectionType;
import smartgridtopo.NetworkNodeType;
import smartgridtopo.SmartMeterType;

/**
 * A sample validator interface for {@link smartgridtopo.Repository}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RepositoryValidator {
    boolean validate();

    boolean validateContainsSmartMeterTypes(EList<SmartMeterType> value);

    boolean validateContainsConnectionType(EList<ConnectionType> value);

    boolean validateContainsNetworkNodeTypes(EList<NetworkNodeType> value);
}
